name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
      #- name: Remove source maps from app
      #  run: rm dist/assets/*.js.map
      - name: Upload app artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy
    steps:
      - name: Deploy to GitHub pages
        uses: actions/deploy-pages@v4
